### PR TITLE
Jordan work

### PR DESCRIPTION
**Pull request by jordan-heemskerk**
Added a basic server to do pre and post processing from s3 files... just need to kick off the EMR job from python still.. should be able to use this 

http://boto.cloudhackers.com/en/latest/emr_tut.html

Basically the plan will be that from angular you will:
- Upload the raw file to s3://facebook-analysis/raw/<name>
- Call the web server at /start_job/<name>
- Poll the web server at /get_job/<name> until it returns a png!

### CODE REVIEW

**Comment by jordan-heemskerk** [comment]
@eburdon @ShovelHand

**Comment by eburdon** [comment]
Looks awesome! I may message you a million times to get this up and running locally w/bottle... but I'll give this a go, then try and get it on it's own bona-fide server :) 

I'll merge in with after a :+1: from @ShovelHand 

...

:+1:

**Comment by ShovelHand** [comment]
Amazing, Jordan.
Besides writing up the lambda stuff on the wiki, what else can I do for the
project? I don't feel awesome that I joined the team after you guys did
most of the real work and then couldn't come through for you on anything.

**Comment by eburdon** [comment]
@ShovelHand are you available tomorrow afternoon? If I get stuck on some of the server work, maybe we could think things through together (remotely).

Otherwise, I'm not too sure what else needs to be done, except just a brief test to make sure everything's happy, and a sketch of the entire architecture. E.g., with web interface, this new server, etc... We don't need to give the prof a demo either, although you guys are free to do one without me.

**Pull request merged**
