### PR TITLE
Wc.go hadoop prep

### PR DESCRIPTION
**Pull request by jordan-heemskerk**
- Cleaned out a bunch of stuff that shouldn't be in the repo
- Restructured wc.go to work with Hadoop streaming, first step in getting it to go on EMR
- Restructure graphbuilder.go to work with new wc.go outputs

### CODE REVIEW

**Comment by jordan-heemskerk** [comment]
@eburdon this too!

**Comment by jordan-heemskerk** [comment]
ec01ea0 is the crowning achievement... see this https://github.com/fvbock/trie/pull/2

**Comment by eburdon** [comment]
:open_mouth: You contributed to open source?! NIIIIIIIIIIIIICE

Just looking through the files now... I was thinking that once this is stable, we'd just fire up the smallest EC2 cluster and run EMR on that instead of spot instances until the 12th. Shouldn't be too expensive and would prevent Lambda from having to configure every time. Thoughts?

**Comment by jordan-heemskerk** [comment]
> I was thinking that once this is stable, we'd just fire up the smallest EC2 cluster and run EMR on that instead of spot instances until the 12th. Shouldn't be too expensive and would prevent Lambda from having to configure every time. Thoughts?

My thoughts exactly. We can spin up a small EMR cluster and leave it running. Lambda can just submit jobs to it using the API (available for most major languages) and then fetch the results from S3 when they are available.

**Comment by eburdon** [comment]
:+1: Just for deleting all the junk alone... I packaged the existing repo just for safety's sake.

Otherwise, looks great, and the plan sounds solid! Merge when ready.

**Comment by eburdon** [comment]
To confirm, looks like there's 1 input, 1 output now?

**Comment by jordan-heemskerk** [comment]
I don't have permission to merge in this repo I don't think. You can just do it if you want, or gimme god mode :P.

**Comment by jordan-heemskerk** [comment]
Input and output all happens over STDIN and STDOUT now, as required by hadoop streaming. There is one input, it controls whether the execution is mapping or reducing.

**Comment by eburdon** [comment]
haha ok. Alex can get the command needed to run from lambda from this codebase / readme?

**Comment by jordan-heemskerk** [comment]
> Alex can get the command needed to run from lambda from this codebase / readme?

@eburdon is he in this repo yet? Have him ask me, its going to depend on what he is calling it from

**Pull request merged**
